<?php
/** @var \Elogic\Blog\Block\Article\View $block */
$article = $block->getArticle();
?>
<div class="article">
    <div class="article title">
        <h1> <?= $article["title"] ?> </h1>
    </div>
    <div class="article author">
        <h2> <?= $article["author"] ?> </h2>
    </div>
    <div class="article desc">
        <h3> <?= $article["desc"] ?> </h3>
    </div>
    <div class="article dates">
        <span> Created at <?= $article["created_at"] ?>, last update <?= $article["updated_at"] ?></span>
    </div>
    <div class="article dates">
        <p> <?= $article["content"] ?></p>
    </div>
</div>
