<?php /** @var Magento\Framework\View\Element\Template $block */

use Elogic\Linkedin\Model\Config\Source\NoOptionalRequired;

?>
<?php $attributeStatus = $block->getData('attribute_status') ?>
<fieldset class="fieldset create account"
    <?php if ($attributeStatus == NoOptionalRequired::IS_REQUIRED) : ?>
        data-hasrequired="<?php /* @escapeNotVerified */
        echo __('* Required Fields') ?>"
    <?php endif; ?> >
    <legend class="legend">
        <span><?php /* @escapeNotVerified */
            echo __('Additional Information') ?></span>
    </legend>
    <br>
    <div
        class="field linkedin_profile<?php if ($attributeStatus == NoOptionalRequired::IS_REQUIRED) : ?> required<?php endif; ?>">
        <label class="label" for="email">
            <span><?= $block->escapeHtml(__('Linkedin Profile')) ?></span>
        </label>
        <div class="control">
            <input type="text" name="linkedin_profile" id="linkedin_profile" title="<?php /* @escapeNotVerified */
            echo __('Linkedin Profile') ?>" class="input-text"
                   data-validate="{<?php if ($attributeStatus == NoOptionalRequired::IS_REQUIRED) : ?>required:true, <?php endif; ?>'validate-url':true, 'maxlength':250}"
                   autocomplete="off"
                   value="<?= $block->getData('linkedin_attribute_data') ?>">
        </div>
    </div>
</fieldset>

